### ISSUE TITLE
Why is it that some Smiles didn't come up with 3D fingerprints?

### ISSUE THREAD

**Issue by Mryangkaitong** [keiserlab/e3fp#32]
```
from e3fp.pipeline import fprints_from_smiles
confgen_params = {'max_energy_diff': 10.0, 'first': 3}
fprint_params = {'bits': 4096, 'radius_multiplier': 1.5, 'rdkit_invariants': True,'level':6}
smiles = "Brc1ccc(-c2nc(-c3ccccc3)c(-c3ccncc3)[nH]2)cc1"
fprints = fprints_from_smiles(smiles, "ritalin", confgen_params=confgen_params, fprint_params=fprint_params)
print(fprints)
```
running result:
[Fingerprint(indices=array([114, 168, 304, 416, 561, 634, 881, 897, 994, 1084, 1378, 1527, 1585, 1647, 1738, 1749, 1826, 2060, 2126, 2227, 2231, 2249, 2429, 2525, 2583, 2597, 2609, 2621, 2714, 2793, 2834, 3007, 3047, 3095, 3107, 3131, 3190, 3382, 3537, 3624, 3795, 3864, 3879, 3913, 3917, 4052, 4053]), level=6, bits=4096, name=ritalin_0), Fingerprint(indices=array([114, 168, 304, 416, 561, 634, 881, 897, 994, 996, 1084, 1378, 1527, 1585, 1647, 1738, 1749, 2060, 2126, 2227, 2231, 2249, 2429, 2525, 2583, 2597, 2609, 2621, 2714, 2793, 2834, 3007, 3047, 3095, 3107, 3131, 3190, 3231, 3382, 3537, 3624, 3795, 3864, 3913, 3917, 4052, 4053]), level=6, bits=4096, name=ritalin_1)]

There'S no ritalin_2  ,What should I do? Or that I have no parameters, right?  thanks @sdaxen

**Comment by sdaxen** [comment]
You will see fewer than the requested number of conformers (in this case the first 3) whenever all additional conformers are too similar to already accepted low energy conformers (controlled by `'rmsd_cutoff'`) or when the energy of additional conformers is greater than some threshold above that of the lowest energy conformer (controlled by `'max_energy_diff'`).

In this case, the culprit is physical similarity. You can see this by adding `'rmsd_cutoff': 0` to `confgen_params`, but I don't recommend doing this, as the additional conformer is identical to the second.

**Comment by Mryangkaitong** [comment]
> You will see fewer than the requested number of conformers (in this case the first 3) whenever all additional conformers are too similar to already accepted low energy conformers (controlled by `'rmsd_cutoff'`) or when the energy of additional conformers is greater than some threshold above that of the lowest energy conformer (controlled by `'max_energy_diff'`).
> 
> In this case, the culprit is physical similarity. You can see this by adding `'rmsd_cutoff': 0` to `confgen_params`, but I don't recommend doing this, as the additional conformer is identical to the second.

OK ,thanks
